<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="wheel_steered">

  <xacro:property name="steering_link_y" value="${wheel_length + 0.1}" />
  <xacro:property name="steering_link_xz" value="0.1" />

  <xacro:include filename="$(find urdf_geometry_parser)/test/urdf/wheel.xacro" />

  <xacro:macro name="wheel_steered" params="wheel_prefix parent_link left_right *joint_origin ">
    <link name="${wheel_prefix}_steering">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${steering_link_xz} ${steering_link_y} ${steering_link_xz}" />
        </geometry>
        <material name="blue">
          <color rgba="0.2 0.2 0.6 1" />
        </material>
      </visual>
    </link>

    <joint name="${wheel_prefix}_steering_joint" type="revolute">
      <limit lower="${-M_PI/6}" upper="${M_PI/6}" effort="1000.0" velocity="2.0" />
      <axis xyz="0 0 1" />
      <parent link="${parent_link}" />
      <child link="${wheel_prefix}_steering" />
      <xacro:insert_block name="joint_origin" />
    </joint>

    <xacro:wheel wheel_prefix="${wheel_prefix}" parent_link="${wheel_prefix}_steering" left_right="${left_right}">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:wheel>
  </xacro:macro>
</robot>
