gripper:
#  type: position_controllers/JointTrajectoryController
#  joints:
#     - finger_joint
#  constraints:
#      goal_time: 0.6
#      stopped_velocity_tolerance: 0.05
#      finger_joint: {trajectory: 0.1, goal: 0.1}
#  stop_trajectory_duration: 0.5
#  state_publish_rate:  25
#  action_monitor_rate: 10

  type: "position_controllers/GripperActionController"
  joint: finger_joint
